#server.port: 8084
#spring:
#  jpa:
#    hibernate.ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#  datasource:
#    url: jdbc:mysql://localhost:3306/real-estate?serverTimezone=UTC
##    username: real-estate
##    password: real-estate