DROP TABLE IF EXISTS TBL_ESTATE;

CREATE TABLE TBL_ESTATE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    number INT(11) NOT NULL,
    owner VARCHAR(255) NOT NULL,
    size DOUBLE NOT NULL,
    value INT(11) NOT NULL,
    quantity INT(11) NOT NULL,
    tax DOUBLE NOT NULL,
)